import { createResolver } from "astro-integration-kit";
import { fileFactory } from "../utils";

const { resolve } = createResolver(import.meta.url);
const typesDTS = fileFactory();

typesDTS.addLines(`declare module 'astrolace:types' {
    export type SlAlert = import('${resolve('../types/index.ts')}').SlAlert;
    export type SlAnimatedImage = import('${resolve('../types/index.ts')}').SlAnimatedImage;
    export type SlAnimation = import('${resolve('../types/index.ts')}').SlAnimation;
    export type SlAvatar = import('${resolve('../types/index.ts')}').SlAvatar;
    export type SlBadge = import('${resolve('../types/index.ts')}').SlBadge;
    export type SlBreadcrumb = import('${resolve('../types/index.ts')}').SlBreadcrumb;
    export type SlBreadcrumbItem = import('${resolve('../types/index.ts')}').SlBreadcrumbItem;
    export type SlButton = import('${resolve('../types/index.ts')}').SlButton;
    export type SlButtonGroup = import('${resolve('../types/index.ts')}').SlButtonGroup;
    export type SlCard = import('${resolve('../types/index.ts')}').SlCard;
    export type SlCarousel = import('${resolve('../types/index.ts')}').SlCarousel;
    export type SlCarouselItem = import('${resolve('../types/index.ts')}').SlCarouselItem;
    export type SlCheckbox = import('${resolve('../types/index.ts')}').SlCheckbox;
    export type SlColorPicker = import('${resolve('../types/index.ts')}').SlColorPicker;
    export type SlCopyButton = import('${resolve('../types/index.ts')}').SlCopyButton;
    export type SlDetails = import('${resolve('../types/index.ts')}').SlDetails;
    export type SlDialog = import('${resolve('../types/index.ts')}').SlDialog;
    export type SlDivider = import('${resolve('../types/index.ts')}').SlDivider;
    export type SlDrawer = import('${resolve('../types/index.ts')}').SlDrawer;
    export type SlDropdown = import('${resolve('../types/index.ts')}').SlDropdown;
    export type SlFormatBytes = import('${resolve('../types/index.ts')}').SlFormatBytes;
    export type SlFormatDate = import('${resolve('../types/index.ts')}').SlFormatDate;
    export type SlFormatNumber = import('${resolve('../types/index.ts')}').SlFormatNumber;
    export type SlIcon = import('${resolve('../types/index.ts')}').SlIcon;
    export type SlIconButton = import('${resolve('../types/index.ts')}').SlIconButton;
    export type SlImageComparer = import('${resolve('../types/index.ts')}').SlImageComparer;
    export type SlInclude = import('${resolve('../types/index.ts')}').SlInclude;
    export type SlInput = import('${resolve('../types/index.ts')}').SlInput;
    export type SlMenu = import('${resolve('../types/index.ts')}').SlMenu;
    export type SlMenuItem = import('${resolve('../types/index.ts')}').SlMenuItem;
    export type SlMenuLabel = import('${resolve('../types/index.ts')}').SlMenuLabel;
    export type SlMutationObserver = import('${resolve('../types/index.ts')}').SlMutationObserver;
    export type SlOption = import('${resolve('../types/index.ts')}').SlOption;
    export type SlPopup = import('${resolve('../types/index.ts')}').SlPopup;
    export type SlProgressBar = import('${resolve('../types/index.ts')}').SlProgressBar;
    export type SlProgressRing = import('${resolve('../types/index.ts')}').SlProgressRing;
    export type SlQrCode = import('${resolve('../types/index.ts')}').SlQrCode;
    export type SlRadio = import('${resolve('../types/index.ts')}').SlRadio;
    export type SlRadioButton = import('${resolve('../types/index.ts')}').SlRadioButton;
    export type SlRadioGroup = import('${resolve('../types/index.ts')}').SlRadioGroup;
    export type SlRange = import('${resolve('../types/index.ts')}').SlRange;
    export type SlRating = import('${resolve('../types/index.ts')}').SlRating;
    export type SlRelativeTime = import('${resolve('../types/index.ts')}').SlRelativeTime;
    export type SlResizeObserver = import('${resolve('../types/index.ts')}').SlResizeObserver;
    export type SlSelect = import('${resolve('../types/index.ts')}').SlSelect;
    export type SlSkeleton = import('${resolve('../types/index.ts')}').SlSkeleton;
    export type SlSpinner = import('${resolve('../types/index.ts')}').SlSpinner;
    export type SlSplitPanel = import('${resolve('../types/index.ts')}').SlSplitPanel;
    export type SlSwitch = import('${resolve('../types/index.ts')}').SlSwitch;
    export type SlTab = import('${resolve('../types/index.ts')}').SlTab;
    export type SlTabGroup = import('${resolve('../types/index.ts')}').SlTabGroup;
    export type SlTabPanel = import('${resolve('../types/index.ts')}').SlTabPanel;
    export type SlTag = import('${resolve('../types/index.ts')}').SlTag;
    export type SlTextarea = import('${resolve('../types/index.ts')}').SlTextarea;
    export type SlTooltip = import('${resolve('../types/index.ts')}').SlTooltip;
    export type SlTree = import('${resolve('../types/index.ts')}').SlTree;
    export type SlTreeItem = import('${resolve('../types/index.ts')}').SlTreeItem;
    export type SlVisuallyHidden = import('${resolve('../types/index.ts')}').SlVisuallyHidden;
    export type VirtualElement = import('${resolve('../types/index.ts')}').VirtualElement;
};`);

export const typesFile = typesDTS.text();